# Generated by Django 3.2.5 on 2021-08-31 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataFileExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=400)),
                ('filepath', models.FileField(upload_to='excel/')),
                ('uploader', models.CharField(max_length=200)),
                ('upload_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='date uploaded')),
            ],
        ),
        migrations.CreateModel(
            name='FileExcelHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=400)),
                ('filepath', models.CharField(max_length=600)),
                ('header', models.TextField()),
                ('sheetname', models.CharField(max_length=400)),
                ('filefrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datamanage.userdatafileexcel')),
            ],
        ),
    ]
