# Generated by Django 3.2.5 on 2021-08-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserMathModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400)),
                ('expression', models.TextField()),
                ('coefficient', models.CharField(max_length=400)),
                ('variable', models.CharField(max_length=400)),
                ('desc', models.TextField()),
                ('remake', models.CharField(max_length=600)),
            ],
        ),
    ]
